// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Random = require("bs-platform/lib/js/random.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

var component = ReasonReact.statelessComponent("Foo");

function make(name, age, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("button", undefined, age !== undefined ? " hi 👋 " + (String(name) + (" age " + (String(Js_primitive.valFromOption(age)) + ""))) : " hi 👋 " + (String(name) + ""));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

Random.self_init(/* () */0);

var $$break = /* record */[/* contents */false];

while(!$$break[0]) {
  if (Random.$$int(10) === 3) {
    $$break[0] = true;
  } else {
    console.log("hello");
  }
};

var me = /* record */[
  /* age */20,
  /* name */"Big Reason"
];

var me2 = /* record */[
  /* age */20,
  /* name */"Big Reason"
];

var me3 = /* record */[
  /* age */20,
  /* name */"Big Reason"
];

exports.component = component;
exports.make = make;
exports.me = me;
exports.me2 = me2;
exports.me3 = me3;
exports.$$break = $$break;
/* component Not a pure module */
