var myString;
var myNum;
var myBool;
var myVar;
var strArr;
myString = "wewew" + "wewew";
myNum = 1;
myBool = false;
myVar = 5;
strArr = ["Hello", "World"];
var numArr = [1, 2, 3, 4];
var strArray;
console.log(myString);
console.log(myBool);
console.log(myVar);
console.log(strArr);
console.log(numArr);
